=== kinicles/kinicles/data/dtd/config.dtd
<!ELEMENT config (#PCDATA | screen | projection | input | sleep | graphic | graphic_device | inferred | opencl | camera | audio)*>
<!ELEMENT screen (#PCDATA)*>
<!ATTLIST screen
	width CDATA #REQUIRED
	height CDATA #REQUIRED
	fullscreen CDATA #REQUIRED
	vsync CDATA #REQUIRED
	stereo CDATA #REQUIRED
>
<!ELEMENT projection (#PCDATA)*>
<!ATTLIST projection
	fov CDATA #REQUIRED
	near CDATA #REQUIRED
	far CDATA #REQUIRED
>
<!ELEMENT input (#PCDATA)*>
<!ATTLIST input
	key_repeat CDATA #REQUIRED
	ldouble_click CDATA #REQUIRED
	mdouble_click CDATA #REQUIRED
	rdouble_click CDATA #REQUIRED
>
<!ELEMENT sleep (#PCDATA)*>
<!ATTLIST sleep
	time CDATA #REQUIRED
>
<!ELEMENT graphic (#PCDATA)*>
<!ATTLIST graphic
	filtering CDATA #REQUIRED
	anisotropic CDATA #REQUIRED
	anti_aliasing CDATA #REQUIRED
>
<!ELEMENT graphic_device (#PCDATA)*>
<!ATTLIST graphic_device
	disabled_extensions CDATA #REQUIRED
	force_device CDATA #REQUIRED
	force_vendor CDATA #REQUIRED
>
<!ELEMENT inferred (#PCDATA)*>
<!ATTLIST inferred
	scale CDATA #REQUIRED
>
<!ELEMENT opencl (#PCDATA)*>
<!ATTLIST opencl
	platform CDATA #REQUIRED
	clear_cache CDATA #REQUIRED
>
<!ELEMENT camera (#PCDATA)*>
<!ATTLIST camera
	position CDATA #REQUIRED
	rotation CDATA #REQUIRED
>
<!ELEMENT audio (#PCDATA)*>
<!ATTLIST audio
	playback CDATA #REQUIRED
	fake_spectrum CDATA #REQUIRED
>

=== kinicles/kinicles/data/config.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE config PUBLIC "-//A2E/config" "config.dtd">
<config>
	<!-- screen resolution and fullscreen/vsync settings (stereo serves no purpose right now) -->
	<screen width="1280" height="720" fullscreen="0" vsync="1" stereo="0"/>
	<!-- initial camera position and x/y rotation -->
	<camera position="0.0,-12.0,-9.0" rotation="5.0,180.0"/>
	<!-- audio settings
	 playback the recorded audio (due to stability issues this should stay off): true|false
	 fake_spectrum (if there is no audio input, enable this to get a random spectrum): true|false
	-->
	<audio playback="false" fake_spectrum="false" />
	<!-- you might want to change the field of view, but near/far should remain at 1/1000 -->
	<projection fov="72.0" near="1.0" far="1000.0"/>
	<!-- there should be no need to change these -->
	<input key_repeat="0" ldouble_click="10" mdouble_click="10" rdouble_click="10"/>
	<!-- this will sleep the program for the specified amount of milliseconds after each rendered frame -->
	<sleep time="0"/>
	<!--
	 filtering options: POINT, LINEAR, BILINEAR, TRILINEAR
	 anisotropic options: 0 (disabled), 1 - 16
	 anti_aliasing options: NONE, FXAA, 2xSSAA, 4/3xSSAA+FXAA, 2xSSAA+FXAA (others are currently unsupported)
	-->
	<graphic filtering="TRILINEAR" anisotropic="16" anti_aliasing="4/3xSSAA+FXAA"/>
	<!--
	 this sets the scale of the geometry and light buffer:
	 0 = 50%, 1 = 62.5%, 2 = 75%, 3 = 87.5%, 4 = 100%
	 it is however not recommended to change this option!
	-->
	<inferred scale="4"/>
	<!-- unless you know what you're doing, don't change the following settings -->
	<graphic_device disabled_extensions="" force_device="" force_vendor=""/>
	<opencl platform="0" clear_cache="1"/>
</config>
